version: "3.7"
services:
  dbt:
    image: dbt-labs/dbt-spark:latest
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - commit_ref=v1.8.0
    depends_on:
      - dbt-hive-metastore
    privileged: true
    volumes:
      - $PWD:$PWD
    working_dir: $PWD
    environment:
      TESTCONTAINERS_RYUK_DISABLED: 'true'
      SPARK_JARS_REPOSITORIES: ${SPARK_JARS_REPOSITORIES:-https://repo1.maven.org/}
      DOCKER_HOST: "http://dind.docker.internal:2375"
  dbt-hive-metastore:
    image: postgres:9-alpine
    hostname: metastore.docker.internal
    volumes:
      - ./.hive-metastore/:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore
  dind:
    hostname: dind.docker.internal
    privileged: true
    image: "docker:dind"
    environment:
      DOCKER_TLS_CERTDIR:
